kind: Namespace
apiVersion: v1
metadata:
  name: kube-fip
  labels:
    app: kube-fip
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-fip
  namespace: kube-fip
  labels:
    app: kube-fip
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-fip-read
  labels:
    app: kube-fip
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - configmaps
  verbs: ["list", "watch"]
- apiGroups: ["kubefip.k8s.binbash.org"]
  resources:
  - floatingips
  - floatingipranges
  verbs: ["get", "list", "watch", "create", "update"]
- apiGroups: ["provisioning.cattle.io"]
  resources:
  - clusters
  verbs: ["get", "list"]
- apiGroups: ["rke-machine-config.cattle.io"]
  resources:
  - harvesterconfigs
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-fip-read
  labels:
    app: kube-fip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-fip-read
subjects:
- kind: ServiceAccount
  name: kube-fip
  namespace: kube-fip
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-fip-kubeconfig-read
  namespace: fleet-default
  labels:
    app: kube-fip
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
    - get
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-fip-kubeconfig-read
  namespace: fleet-default
  labels:
    app: kube-fip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-fip-kubeconfig-read
subjects:
- kind: ServiceAccount
  name: kube-fip
  namespace: kube-fip
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-fip
  namespace: kube-fip
  labels:
    app: kube-fip
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
    - get
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-fip
  namespace: kube-fip
  labels:
    app: kube-fip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-fip
subjects:
- kind: ServiceAccount
  name: kube-fip
  namespace: kube-fip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-fip-config
  namespace: kube-fip
data:
  logLevel: "Info"
  traceIpamData: "false"
  kubevipUpdate: "false"
  operateGuestClusterInterval: "480"
  kubevipGuestInstall: "clusterlabel"
  kubevipNamespace: kube-system
  kubevipChartRepoUrl: "https://kube-vip.io/helm-charts"
  kubevipChartValues: |
    config:
      vip_interface: enp1s0
    image:
      repository: plndr/kube-vip
      tag: v0.4.1
    nodeSelector:
      node-role.kubernetes.io/master: 'true'
  kubevipCloudProviderChartValues: |
    image:
      repository: kubevip/kube-vip-cloud-provider
      tag: 0.1
  removeHarvesterCloudProvider: "false"
  harvesterCloudProviderNamespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-fip
  name: kube-fip-operator
  namespace: kube-fip
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-fip-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-fip-operator
    spec:
      containers:
      - name: kube-fip-operator
        image: ghcr.io/joeyloman/kube-fip-operator:v0.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: kube-fip
      terminationGracePeriodSeconds: 30
